version: '3.2'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=thenewboston_pv
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - C_FORCE_ROOT=true
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./scripts/docker_entrypoints/initdb.d:/docker-entrypoint-initdb.d

  bank:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=d2621d30bc323ea35fe1c4fb11b4babb7fd4c1c0593805f011caedf7b7ce0031
      - NODE_IDENTIFIER=ce236a006a0aec488ad8e5161dd018b2ce84d9e4d9adc897eca7fb112864198f
      - NODE_PORT=8004
      - REDIS_DB=3
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_bank
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    env_file:
      - .env
    entrypoint: /opt/project/scripts/docker_entrypoints/entrypoint.sh
    volumes:
      - .:/opt/project
      - ./media/bank:/opt/project/media
    ports:
      - 8004:8000
    links:
      - pv
      - db
      - redis
    depends_on:
      - pv
      - db
      - redis

  pv:
    image: docker.pkg.github.com/thenewboston-developers/validator/validator:latest
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=731f928711f30257d20bde471200c11975009415b4c6f596e7ee81bfed1a033b
      - NODE_IDENTIFIER=ed3b6d8e7ba1819ccedb17f9a7427b8e76b22dccf2bc130fc2386daf86ec80d3
      - NODE_PORT=8001
      - REDIS_DB=0
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_pv
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    env_file:
      - .env
    entrypoint: /opt/project/scripts/docker_entrypoints/entrypoint_pv.sh
    volumes:
      - ./media/pv:/opt/project/media
    ports:
      - 8001:8000
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  cv1:
    image: docker.pkg.github.com/thenewboston-developers/validator/validator:latest
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=46a23fd52b2690f5acf56654489fd67b3734a52f35a2b7827f5caeaa06c0c0a5
      - NODE_IDENTIFIER=8ecf3ff5cc8b6b9db7077f9776043b21d22a59544056add03bdfa4c8b35a13bd
      - NODE_PORT=8002
      - REDIS_DB=1
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_cv1
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    env_file:
      - .env
    entrypoint: /opt/project/scripts/docker_entrypoints/entrypoint_cv.sh
    volumes:
      - ./media/cv1:/opt/project/media
    ports:
      - 8002:8000
    links:
      - pv
      - db
      - redis
    depends_on:
      - pv
      - db
      - redis

  cv2:
    image: docker.pkg.github.com/thenewboston-developers/validator/validator:latest
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=1c7822c93d914ac40fc11d7bd71959d5aadb1ecd07fbffc7d9c481ccd043d4a9
      - NODE_IDENTIFIER=73ca63ab2ab4ad8a2f48baa321bce17f8840f7355211b32a288b4e8c3e5a7a4d
      - NODE_PORT=8003
      - REDIS_DB=2
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_cv2
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    env_file:
      - .env
    entrypoint: /opt/project/scripts/docker_entrypoints/entrypoint_cv.sh
    volumes:
      - ./media/cv2:/opt/project/media
    ports:
      - 8003:8000
    links:
      - pv
      - db
      - redis
    depends_on:
      - pv
      - db
      - redis

  celery_bank:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=d2621d30bc323ea35fe1c4fb11b4babb7fd4c1c0593805f011caedf7b7ce0031
      - REDIS_DB=3
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_bank
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    command: celery -A config.settings worker -l debug
    volumes:
      - .:/opt/project
    links:
      - bank
      - db
      - redis
    depends_on:
      - db
      - redis
#
#  celery_pv:
#    image: docker.pkg.github.com/thenewboston-developers/validator/validator:latest
#    environment:
#      - DJANGO_APPLICATION_ENVIRONMENT=local
#      - NETWORK_SIGNING_KEY=731f928711f30257d20bde471200c11975009415b4c6f596e7ee81bfed1a033b
#      - REDIS_DB=0
#      - REDIS_HOST=redis
#      - POSTGRES_HOST=db
#      - POSTGRES_DB=thenewboston_pv
#      - POSTGRES_USER=thenewboston
#      - POSTGRES_PASSWORD=thenewboston
#      - SECRET_KEY=somesecret
#    command: celery -A config.settings worker -l debug -Q celery,block_queue,confirmation_block_queue
#    links:
#      - pv
#      - db
#      - redis
#    depends_on:
#      - db
#      - redis
#
#  celery_cv1:
#    image: docker.pkg.github.com/thenewboston-developers/validator/validator:latest
#    environment:
#      - DJANGO_APPLICATION_ENVIRONMENT=local
#      - NETWORK_SIGNING_KEY=46a23fd52b2690f5acf56654489fd67b3734a52f35a2b7827f5caeaa06c0c0a5
#      - REDIS_DB=1
#      - REDIS_HOST=redis
#      - POSTGRES_HOST=db
#      - POSTGRES_DB=thenewboston_cv1
#      - POSTGRES_USER=thenewboston
#      - POSTGRES_PASSWORD=thenewboston
#      - SECRET_KEY=somesecret
#    command: celery -A config.settings worker -l debug -Q celery,block_queue,confirmation_block_queue
#    links:
#      - cv1
#      - db
#      - redis
#    depends_on:
#      - db
#      - redis
#
#  celery_cv2:
#    image: docker.pkg.github.com/thenewboston-developers/validator/validator:latest
#    environment:
#      - DJANGO_APPLICATION_ENVIRONMENT=local
#      - NETWORK_SIGNING_KEY=1c7822c93d914ac40fc11d7bd71959d5aadb1ecd07fbffc7d9c481ccd043d4a9
#      - REDIS_DB=2
#      - REDIS_HOST=redis
#      - POSTGRES_HOST=db
#      - POSTGRES_DB=thenewboston_cv2
#      - POSTGRES_USER=thenewboston
#      - POSTGRES_PASSWORD=thenewboston
#      - SECRET_KEY=somesecret
#    command: celery -A config.settings worker -l debug -Q celery,block_queue,confirmation_block_queue
#    links:
#      - cv2
#      - db
#      - redis
#    depends_on:
#      - db
#      - redis

volumes:
  postgresql-data:
    driver: local

  redis-data:
    driver: local
